<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : http://www.mybb.com/
// Compatible version of MyBB : 1805
// Last edited in MyBB Editor by : chack1172
// Last edited date : Sat, 22 Aug 2015 19:40:28 +0000
// --------------------------------------------------------------------------------

$l['file_title'] = 'File Manager';
$l['file_nav_root'] = 'root';
$l['file_nav_edit'] = 'Edit file: {1}';
$l['file_nav_delete_file'] = 'Delete file: {1}';
$l['file_nav_delete_dir'] = 'Delete folder: {1}';
$l['file_nav_newdir'] = 'New Folder';
$l['file_nav_newfile'] = 'New File';
$l['file_nav_upload'] = 'Upload Files';
$l['file_sub_name'] = 'File Manager';
$l['file_sub_name_desc'] = 'You can manage files here';
$l['file_sub_nfile'] = 'New File';
$l['file_sub_nfile_desc'] = 'You can create a new file here';
$l['file_sub_ndir'] = 'New Folder';
$l['file_sub_ndir_desc'] = 'You can create a new folder here';
$l['file_sub_upload'] = 'Upload Files';
$l['file_sub_upload_desc'] = 'You can uploads files here';
$l['file_file'] = 'File';
$l['file_actions'] = 'Actions';
$l['file_edit'] = 'Edit';
$l['file_edit_title'] = 'Edit file: {1}/{2}';
$l['file_delete'] = 'Delete';
$l['file_delete_file_title'] = 'Delete file: {1}/{2}';
$l['file_delete_file_desc'] = 'Are you sure you want to delete this file?';
$l['file_delete_dir_title'] = 'Delete folder: {1}/';
$l['file_delete_dir_desc'] = 'Are you sure you want to delete this folder and its contents?';
$l['file_delete_warn'] = 'This action is irreversible, you may lose important files.';
$l['file_newdir_title'] = 'Folder creation in {1}/';
$l['file_newdir_desc'] = 'Folder Name';
$l['file_newdir_subdesc'] = 'Here you can insert the name of the new folder.';
$l['file_newfile_title'] = 'File creation in {1}/';
$l['file_newfile_desc'] = 'File Name';
$l['file_newfile_subdesc'] = 'Here you can insert the name and the extension of the new file';
$l['file_upload_title'] = 'Files Upload';
$l['file_upload_select'] = 'Select Files';
$l['file_upload_select_desc'] = 'Select files to upload';
$l['file_upload_files'] = 'Selected Files';
$l['file_upload_files_no'] = 'Select a file from the button above.';
$l['file_upload_file_name'] = "File Name";
$l['file_upload_file_size'] = "File Size";
$l['file_upload_no_file'] = "You did not selected any files.";
$l['file_upload_exists'] = "The file {1} already exists in this folder. No file has been uploaded.";
$l['file_upload_part_uploaded'] = "{1} files of {2} uploaded.";
$l['file_upload_uploaded'] = "The selected files have been uploaded successfully.";
$l['file_rename'] = 'Rename';
$l['file_button_save'] = 'Save and close';
$l['file_button_quick_save'] = 'Save and continue';
$l['file_button_close'] = 'Close';
$l['file_button_delete'] = 'Delete';
$l['file_button_newdir'] = 'Create folder';
$l['file_button_newfile'] = 'Create file';
$l['file_button_rename'] = 'Rename';
$l['file_button_cancel'] = 'Cancel';
$l['file_button_upload'] = 'Submit files';
$l['file_button_text'] = 'Text editor';
$l['file_button_advanced'] = 'Advanced editor';
$l['file_success_edit'] = 'The file has been saved succesfully';
$l['file_success_delete_file'] = 'The file has been deleted succesfully';
$l['file_success_delete_dir'] = 'The folder has beeen deleted succesfully';
$l['file_success_newdir'] = 'The folder has been created succesfully';
$l['file_success_newfile'] = 'The file has been created succesfully';
$l['file_error_exists'] = 'The selected file does not exists.';
$l['file_error_exists_dir'] = 'The selected folder does not exists.';
$l['file_error_edit'] = 'Sorry, something went wrong saving the file. Please try again.';
$l['file_error_edit_file'] = 'You didn\'t select a file to be edited.';
$l['file_error_edit_type'] = 'The selected file could not be edited.';
$l['file_error_delete'] = 'Sorry, something went wrong deleting the file/folder. Please try again.';
$l['file_error_delete_root'] = 'You can\'t delete the root of your forum.';
$l['file_error_delete_input'] = 'You didn\'t select a file/folder to be deleted.';
$l['file_error_newdir'] = 'Sorry, something went wrong during the creation of the folder. Please try again.';
$l['file_error_newdir_exists'] = 'There is already a folder with that name.';
$l['file_error_newdir_name'] = 'You are required to enter a folder name.';
$l['file_error_newfile_exists'] = 'There is already a file with that name.';
$l['file_error_newfile_name'] = 'You are required to enter a file name.';
$l['file_error_rename'] = 'Sorry, something went wrong during the rename of the file/folder. Please try again.';
$l['file_success_rename'] = 'The file has been renamed succesfully';
$l['file_success_rename_dir'] = 'The folder has been renamed succesfully';
$l['file_error_rename_exists'] = 'There is already a file or a folder with the new name inserted.';
$l['file_error_rename_not_exists'] = 'The selected file/folder does not exists.';
$l['file_error_rename_name'] = 'You are requred to enter a new name.';
$l['file_error_rename_input'] = 'You didn\'t select a file/folder  to be renamed.';
$l['can_access_file_manager'] = 'Can access to the file manager?';
$l['file_search'] = "Search a file...";
